services:
  web:
    build: .
    ports:
      - "5001:5000"
    
    command: ["/app/wait-for-it.sh", "db:3306", "--", "python", "app.py"]
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: change-me
      MYSQL_DB: Luxe_Fashion
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    depends_on:
      - db
      # opcional, solo si quieres hot reload

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: change-me
      MYSQL_DATABASE: Luxe_Fashion
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
